---

- name: deploy server consul.hcl config file
  template: 
    src: consul-server-config.hcl.j2 
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640

# https://learn.hashicorp.com/consul/advanced/day-1-operations/deployment-guide
- name: deploy server consul.hcl config file
  template: 
    src: consul-server.service
    dest: /etc/systemd/system/consul-server.service
    owner: consul
    group: consul
    mode: 0640