---

- name: Copy across configs
  copy: 
    src: configs
    dest: /etc/consul-template
    owner: consul-template
    group: consul-template
    mode: 0640

- name: Copy across ctmpl files
  copy: 
    src: ctmpl-files
    dest: /etc/consul-template
    owner: consul-template
    group: consul-template
    mode: 0640